# docker-compose.yml
version: '3'
services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
